name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Deploy code
    runs-on: ubuntu-latest

    env:
      AWS_REGION: "us-west-2"
      # TF_VERSION: "1.9.8"
      # TFLINT_VERSION: "0.46.1" # Updated to a more recent version
      # TFSEC_VERSION: "1.28.1" # Updated to a more recent version

    steps:
      - name: "Checkout Github repo"
        uses: actions/checkout@v4

      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Verify Terraform version
        run: terraform --version

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Show TFLint version
        run: tflint --version
